### ISSUE TITLE
Thermos build 56 and opis

### ISSUE THREAD

**Issue by 31trainman** [CyberdyneCC/Thermos#341]
http://pastebin.com/XNk7fHZR

Trying to run opis on server results in a crash

Install mobiscore and opis on server.

mobius core and opis

none

Thermos build 56 

Forge 1614

**Comment by Razorskills** [comment]
I believe Thermos is not supporting Opis.

**Comment by sgdc3** [comment]
Yeah, but why? Just to know ;)

**Comment by ArcasCZ** [comment]
@Robotia and me are trying to figure it out. It has to do somethink with class net/minecraft/world/World.

**Comment by 31trainman** [comment]
trying to use ops to track down mods that are causing lag on a server @sgdc3

**Comment by sgdc3** [comment]
You misunderstood me xD I mean: why opis isn't supported? I'm asking it to the developers.

**Comment by 31trainman** [comment]
Ah my bad was confused.

**Comment by Time6628** [comment]
Use warmroast if you can.

**Comment by dabaer** [comment]
Warmroast is great for finding functions that take a long time, but Opis really allows us to get into the nitty gritty of blocks and entity latency. No server should be without both! I highly vouch for Opis support in Thermos.

**Comment by ArcasCZ** [comment]
How does it looks like?

**Comment by ArcasCZ** [comment]
Here is my try-to-fix MobiusCore - try on your own risk. And let me know if it works. For me it seems working, but I haven't time to test it in wide way.




[MobiusCore-1.2.5-Thermos.jar.gz](https://github.com/CyberdyneCC/Thermos/files/288540/MobiusCore-1.2.5-Thermos.jar.gz)

**Comment by 31trainman** [comment]
@ArcasCZ Your fixed MobiusCore works on build 55

**Comment by ArcasCZ** [comment]
So, today I fixed it in more official way. After @Robotia will create GitHub repo, I'll push out sources.

This fix is still marked as potentialy unsafe, 'cause it changes some things developers added to Thermos in World class (switched from ArrayList to own HashedArrayList). 

Anyway - now you can use this thread to give me feedback.

[MobiusCore-1.2.5_1.7.10-Thermos.jar.gz](https://github.com/CyberdyneCC/Thermos/files/290013/MobiusCore-1.2.5_1.7.10-Thermos.jar.gz)

**Comment by Hoborific** [comment]
console is full of 

[00:45:23 INFO]: Improper type detected for tile entity list in world 0. Regenerating tracking list.
[00:45:28 INFO]: Improper type detected for tile entity list in world -1. Regenerating tracking list.
[00:45:28 INFO]: Improper type detected for tile entity list in world 0. Regenerating tracking list.
[00:45:33 INFO]: Improper type detected for tile entity list in world -1. Regenerating tracking list.

and my entities are sometimes invisible to the client, thermos 57_1614 + your mobicore.

**Comment by ArcasCZ** [comment]
@Hoborific - This error first appeared to me at KCauldron 201 with Mobius fixed by Prototik.

**Comment by 31trainman** [comment]
Still can't use regular mobiusCore on build 57. the one @ArcasCZ made works fine though.

**Comment by ArcasCZ** [comment]
@31trainman The regular one will never work with Thermos. You have to use edited one.

**Comment by 31trainman** [comment]
Ah ok, this should be put somewhere more prominent

**Comment by ArcasCZ** [comment]
It's on Thermos GitHub main page - in ReadMe...
